config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  resources :packages
  resources :couriers do
    resources :packages
  end  
  
  root 'couriers#index'
  get '*path', to: 'couriers#index'  
  
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
# frozen_string_literal: true

# Model for Courier
class Courier < ApplicationRecord

  has_many :packages

  validates :name,    presence: true
  validates :email,   presence: true
  
end

app/models/package.rb
# frozen_string_literal: true

# Model for Package
class Package < ApplicationRecord

  belongs_to :courier, optional: true

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
# frozen_string_literal: true

# Controller to see the list of Couriers
class CouriersController < ApplicationController
  before_action :set_courier, only: %i[show edit update destroy]

  def index
    @couriers = Courier.all
  end

  def new
    @courier = Courier.new
  end

  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      redirect_to @courier, notice: "Запис про кур'єра було успiшно створено."
    else
      render :new
    end
  end

  def show 
    @package = @courier.packages.build
    @packages = Package.where courier_id: @courier.id
  end

  def edit; end

  def update
    if @courier.update(courier_params)
      redirect_to @courier, notice: "Запис про кур'єра було успiшно видалено."
    else
      render :edit
    end
  end

  def destroy
    @courier.destroy
    redirect_to couriers_url, notice: "Запис про кур'єра було успiшно видалено."
  end


  private

  def set_courier
    @courier = Courier.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def courier_params
    params.require(:courier).permit(:name, :email)
  end
end

app/controllers/packages_controller.rb
# frozen_string_literal: true

# Controller to see the list of Packages
class PackagesController < ApplicationController

  def create
    @package = Package.new(package_params)
    @package.save
    redirect_to root_path, notice: "Запис про посилку було успiшно створено." 
  end
  
  
  private

  def package_params
    params.require(:package).permit(:courier_id, :tracking_number, :delivery_status)
  end  
  
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/courier_helper.rb
# frozen_string_literal: true

module CourierHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/_form.html.haml
= form_with(model: @courier, local: true) do |form|

  - if @courier.errors.any?
    #error_explanation
      %h3
        = pluralize(courier.errors.count, "error")
        Допис не було збережено, оскiльки:
      %ul
        - courier.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label 'Name'
    = form.text_field :name

  .field
    = form.label 'Email'
    = form.text_field :email
  .actions
    = form.submit

app/views/couriers/_package_form.html.haml
%h3
  Додати посилку:

= form_with(model: @package, local: true) do |form|

  .field
    = form.label 'Tracking Number'
    = form.text_field :tracking_number

  .field
    = form.label 'Delivery Status'
    = form.check_box :delivery_status
    
  = form.hidden_field :courier_id, value: @courier.id
    
  .actions
    = form.submit
    
    

app/views/couriers/edit.html.haml
%h4
  "Редагування запису про нового кур'єра:"

= render 'form', checklist: @checklist

app/views/couriers/index.html.haml
%p#notice
  = notice

%h2 
  Кур'єри:

%table
  %thead
    %tr
      %th Title
      %th Description
      %th{:colspan => "3"}
  %tbody
    - @couriers.each do |courier|	
      %tr
      
        %td
          = link_to courier do
            = courier.name
        %td
          = link_to courier do
            = courier.email
        %td
          = link_to 'Переглянути', courier_path(courier)         
          = link_to 'Редагувати', edit_courier_path(courier) 
          = link_to 'Видалити', courier, method: :delete, data: { confirm: "Видалити запис про кур'єра?" }
%br/
= link_to "Створити нового кур'єра", new_courier_path

app/views/couriers/new.html.haml
%h2
  Створення запису про нового кур'єра:

= render 'form', courier: @courier

%br/
= link_to "До списку всiх кур'єрiв", couriers_path 

app/views/couriers/show.html.haml
%p#notice
  = notice

%p
  %strong 
    Iм'я:
  = @courier.name
%p
  %strong 
    Email:
  = @courier.email

%br/
= link_to "Створити нового кур'єра", new_courier_path    

%br/
= link_to 'Редагувати', edit_courier_path(@courier)

%br/
= link_to 'Видалити', @courier, method: :delete, data: { confirm: "Видалити запис про кур'єра?" }

%br/
= link_to "До списку всiх кур'єрiв", couriers_path 

%hr/
- if @courier.packages.count > 0
  - @courier.packages.each do |p|	
    %p
      %b
        Tracking Number:
      = p.tracking_number
        
    %p
      %b
        Delivery Status:
      = p.delivery_status

= render 'package_form', courier: @courier

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>